<?php

namespace OpenSeaWave\Keycloak\Enums;

/**
 * CredentialType enum class.
 *
 * @package OpenSeaWave\Keycloak\Enums
 * @author  Omar Haris
 */
enum CredentialType: string
{
    /**
     * Password credential type.
     *
     * This type is used to represent a password-based credential for user authentication.
     * Typically, users will use this credential to log in with their username and password.
     */
    case PASSWORD = 'password';

    /**
     * OTP (One-Time Password) credential type.
     *
     * This type is used for a One-Time Password (OTP), usually generated by an authenticator app
     * or received via email or SMS. OTP credentials are commonly used for two-factor authentication.
     */
    case OTP = 'otp';

    /**
     * Secret credential type.
     *
     * This type is used for client secrets, often utilized in server-to-server authentication.
     * Typically, it is used by services or applications to authenticate against Keycloak as a client.
     */
    case SECRET = 'secret';
}
